[Rainmeter]
DefaultUpdateDivider=-1
AccurateText=1

@IncludeSettings=#@#settings.inc

OnRefreshAction=[!Draggable "0"][!ClickThrough "1"][!SetWindowPosition "(#WORKAREAX#+#WORKAREAWIDTH#-#W#-#RightMargin#)" "(#WORKAREAY#+#WORKAREAHEIGHT#-#H#-#BottomMargin#)" "0" "0"][!ZPos "2"][!SetTransparency "155"]

[Metadata]
Name=Activate Windows
Author=Reisir&woxile（GPT5.6-Sol）
Information=Displays the "Activate Windows" dialog found on unactivated Windows 10.
Version=1.1.0
License=CC-NC-SA

[Style]
AntiAlias=1
FontColor=125,125,125,255
SolidColor=0,0,0,1
FontFace=Segoe UI

[FirstLineStyle]
FontSize=30
X=#FirstLineX#
Y=#FirstLineY#

[SecondLineStyle]
; Windows uses FontSize 11,3 but rainmeter rounds down to an integer
; So we use CharacterSpacing to workaround the limitation
FontSize=19
InlineSetting=CharacterSpacing | 0.11
Y=0R
X=0r

[IncludeLanguage]
@IncludeLanguage=#@#lang\[#LANGUAGE].inc

[Background]
Meter=Image
W=#W#
H=#H#
SolidColor=0,0,0,0

[FirstLine]
Meter=String
Text=[#FirstLine]
MeterStyle=Style | FirstLineStyle

[SecondLine]
Meter=String
Text=[#SecondLine]
MeterStyle=Style | SecondLineStyle
